/**
 * The bag screen, against a fixture generated by the real backend.
 *
 * `fixtures/bag-appraisal.json` is written by `scripts/make_ui_fixtures.py` through
 * `appraise_bag` and `BagAppraisal.to_json`, and a Python test fails when it drifts.
 * So these assertions are against a payload the backend can actually produce, not
 * against a shape somebody typed out — which is the difference between testing the
 * screen and testing a mock of it.
 *
 * Every case here is one of Phase 5's stated findings from live data. Nothing is
 * hypothetical, and nothing touches a network: the client is a plain object.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { TransportError, clearClient, installClient } from '@poedex/core'
import { VERDICT_HEADLINE } from '@poedex/ui'
import type { BagAppraisalPayload, PoedexClient } from '@poedex/core'
import { BagScreen } from './BagScreen'
import { blocksOf, checkLane, copyFor, floorNote, glyphFor, tallyOf, toRow } from './model'
import fixture from './fixtures/bag-appraisal.json'

const BAG = fixture as unknown as BagAppraisalPayload

interface Harness {
  client: PoedexClient
  fire: (topic: string) => void
}

function harness(answer: () => Promise<BagAppraisalPayload> = async () => BAG): Harness {
  const listeners: { pattern: string; fn: () => void }[] = []
  const client = {
    transport: {
      id: 'http',
      state: 'open',
      call: async () => undefined,
      on: (pattern: string, fn: () => void) => {
        listeners.push({ pattern, fn })
        return () => {}
      },
      connect: () => {},
      close: () => {},
      onStateChange: () => () => {},
    },
    appraisal: { bag: answer },
    prices: { refresh: vi.fn(async () => ({})) },
  } as unknown as PoedexClient
  return {
    client,
    fire: (topic) => listeners.filter((l) => l.pattern === topic).forEach((l) => l.fn()),
  }
}

/**
 * Queries that hold under either profile.
 *
 * `Section` is a labelled group and every row carries `data-uid` in both
 * implementations, so nothing here reaches for a class name or an element type.
 * That is what lets `pnpm run test:compact` run this same file.
 */
const section = (title: string) => screen.getByRole('group', { name: title })

const rowFor = (name: string, scope?: HTMLElement) =>
  within(scope ?? document.body).getByText(name).closest('[data-uid]') as HTMLElement

const rowsIn = (scope: HTMLElement) =>
  Array.from(scope.querySelectorAll<HTMLElement>('[data-uid]'))

/**
 * Open a section that a profile may have collapsed by default.
 *
 * `compact` collapses `trash` and the provenance block at 300 px; `full` does not
 * and its title is not pressable, so the click is a no-op there. Writing the test
 * this way keeps it profile-agnostic without pretending the densities are the same.
 */
const reveal = async (title: string) => {
  // A substring matcher: `compact` prefixes a collapsed title with a caret, and the
  // caret is part of the same text node.
  const label = within(section(title)).queryByText((_text, node) =>
    node?.children.length === 0 && (node.textContent ?? '').includes(title),
  )
  if (label) await userEvent.click(label)
}

/** Select a row through the grid, which draws every row at both densities. */
const inspect = async (name: string) => {
  const grid = screen.getByRole('grid', { name: 'bag layout, by verdict' })
  await userEvent.click(within(grid).getByLabelText(new RegExp(name)))
  return screen.getByRole('group', { name: 'item detail' })
}

async function show(answer?: () => Promise<BagAppraisalPayload>) {
  const built = harness(answer)
  installClient(built.client)
  const view = render(<BagScreen />)
  await waitFor(() => expect(screen.queryByText(/reading the bag/i)).toBeNull())
  return { ...built, view }
}

beforeEach(() => clearClient())
afterEach(() => {
  cleanup()
  clearClient()
})

// -- what the screen has to get right -----------------------------------------

describe('the four verdicts', () => {
  it('gives every verdict its own block, in the order the player acts on them', async () => {
    await show()
    const titles = screen
      .getAllByRole('group')
      .map((node) => node.getAttribute('aria-label'))
      .filter(
        (label): label is string =>
          Boolean(label) && /^(keep|check · |unpriceable|trash)/.test(label!),
      )
    expect(titles).toEqual([
      'keep',
      'check · no price yet',
      'check · priced',
      'unpriceable',
      'trash',
    ])
  })

  it('never folds unpriceable into trash', async () => {
    await show()
    expect(within(section('unpriceable')).getByText('Veiled Scarab')).toBeInTheDocument()
    expect(within(section('trash')).queryByText('Veiled Scarab')).toBeNull()
  })

  it('keeps the unpriceable count in the tally even though it earns nothing', async () => {
    await show()
    const tally = screen.getByRole('group', { name: 'verdict tally' })
    expect(within(tally).getByText('unpriced')).toBeInTheDocument()
    expect(within(tally).getByText(String(BAG.counts.unpriceable))).toBeInTheDocument()
  })

  it('shows an unpriceable row as a dash and a unit count, never as 0c', async () => {
    await show()
    const block = section('unpriceable')
    expect(block.textContent).toContain('174')
    expect(rowFor('Veiled Scarab', block).textContent).toContain('—')
  })
})

describe('the total', () => {
  it('is marked as a floor and says what it leaves out', async () => {
    await show()
    expect(screen.getByText('≥')).toBeInTheDocument()
    const note = floorNote(BAG)!
    expect(screen.getByText(note)).toBeInTheDocument()
    expect(note).toMatch(/excludes 2 unpriceable rows/)
    expect(note).toMatch(/still pricing/)
    expect(note).toMatch(/floor, not a value/)
  })

  it('drops the floor marker when there is no hole', async () => {
    const solid: BagAppraisalPayload = {
      ...BAG,
      items: BAG.items.filter(
        (item) => item.verdict !== 'unpriceable' && !item.pricing,
      ),
      counts: { ...BAG.counts, unpriceable: 0 },
      unpriceable_count: 0,
      unpriceable_stack: 0,
      pricing_count: 0,
      no_listings_count: 0,
      total_is_floor: false,
    }
    await show(async () => solid)
    expect(screen.queryByText('≥')).toBeNull()
  })
})

describe('provenance', () => {
  it('labels which claim each row’s number rests on', async () => {
    await show()
    const keep = section('keep')
    // poe.ninja's index, a trade search and the player's own note are three
    // different assertions about the world, and the row says which it is showing.
    for (const claim of ['ninja', 'trade', 'note']) {
      expect(keep.textContent).toContain(claim)
    }
  })

  it('names the claim in full in the detail pane, including the bulk exchange', async () => {
    // Through the grid rather than the list: `compact` truncates the keep block to
    // five rows and the exchange-priced row is the sixth. The grid draws every row
    // at both densities, which is what makes it a map rather than a summary.
    await show()
    expect((await inspect("Merrick's Ducat")).textContent).toContain('bulk exchange')
  })

  it('says where the league came from, not just which league it is', async () => {
    await show()
    expect(screen.getAllByText(/Allflame \(from the character\)/).length).toBeGreaterThan(0)
  })

  it('shouts when something overrode the character’s league', async () => {
    await show(async () => ({ ...BAG, league_overridden: true, league_source: 'setting' }))
    // Twice on purpose: once in the header subtitle, once in the provenance block.
    expect(screen.getAllByText(/OVERRIDE/).length).toBeGreaterThan(0)
  })

  it('shows the table status and how the type list was discovered', async () => {
    await show()
    await reveal('how this was decided')
    expect(screen.getByText(/36 of 38 candidate types/)).toBeInTheDocument()
  })
})

describe('rows a real bag actually contains', () => {
  it('survives a five-digit stack without abbreviating it', async () => {
    await show()
    expect(screen.getAllByText(/×40,296/).length).toBeGreaterThan(0)
  })

  it('keeps two rows with the same name and different stacks apart', async () => {
    // Asserted on the grid, which draws every row at both densities: `compact`
    // collapses the trash block, and one of these two stacks lives in it. They are
    // two stacks in two slots — merging them by name would move an item.
    await show()
    const grid = screen.getByRole('grid', { name: 'bag layout, by verdict' })
    const cells = within(grid).getAllByLabelText(/Dead Man's Sulphur/)
    expect(cells).toHaveLength(2)
    const labels = cells.map((node) => node.getAttribute('aria-label'))
    expect(labels).toContain("Dead Man's Sulphur ×40296, keep")
    expect(labels).toContain("Dead Man's Sulphur ×7, trash")
  })

  it('shows a gated rare with no price as a dash, with its gate reasoning', async () => {
    await show()
    const row = rowFor('Corpse Ward', section('check · no price yet'))
    expect(row.textContent).toContain('—')
    expect(row.textContent).not.toContain('0c')
    // The gate's claim is printed, because a verdict nobody can argue with is one
    // nobody trusts either. The row carries the signal names at both densities...
    expect(row.textContent).toContain('influence')
    expect(row.textContent).toContain('ilvl')
    // ...and the sentence behind them is one selection away.
    expect((await inspect('Corpse Ward')).textContent).toContain('hunter-influenced')
  })

  it('shows an outstanding tier-3 query as ⋯ rather than as nothing', async () => {
    await show()
    const row = rowFor('Rift Shroud', section('check · no price yet'))
    expect(row.textContent).toContain('⋯')
    expect(row.textContent).toContain('pricing…')
    expect(row.textContent).not.toContain('0c')
  })
})

describe('check, which is doing two jobs', () => {
  it('draws the two jobs as two blocks', async () => {
    await show()
    const unknown = section('check · no price yet')
    const priced = section('check · priced')

    // Job two: the gate flagged it and a trade search is what settles it.
    expect(within(unknown).getByText('Corpse Ward')).toBeInTheDocument()
    expect(within(unknown).getByText('Rift Shroud')).toBeInTheDocument()

    // Job one: a number, just a small one.
    expect(within(priced).getByText('Greater Eldritch Ember')).toBeInTheDocument()
    expect(within(priced).queryByText('Corpse Ward')).toBeNull()
  })

  it('sorts the gate-flagged block by hard-signal count, as the backend ranked it', async () => {
    await show()
    const unknown = section('check · no price yet')
    // Corpse Ward hits two of SPEC §5.2's hard requirements; Rift Shroud one. The
    // backend ranks on that, and the screen partitions without re-sorting.
    expect(rowsIn(unknown)[0]!.textContent).toContain('Corpse Ward')
  })
})

describe('the grid', () => {
  it('is a map: every row is drawn at its own slot, labelled with its verdict', async () => {
    await show()
    const grid = screen.getByRole('grid', { name: 'bag layout, by verdict' })
    expect(within(grid).getByLabelText(/Divine Orb ×3, keep/)).toBeInTheDocument()
    expect(within(grid).getByLabelText(/Veiled Scarab ×174, unpriceable/)).toBeInTheDocument()
  })

  it('selecting a cell fills the detail pane with where the number came from', async () => {
    await show()
    const grid = screen.getByRole('grid', { name: 'bag layout, by verdict' })
    await userEvent.click(within(grid).getByLabelText(/Yoke of Suffering/))
    const detail = screen.getByRole('group', { name: 'item detail' })
    expect(detail.textContent).toContain('your ~price note')
    // The player's own asking price against the index — SPEC §6.3's comparison.
    expect(detail.textContent).toContain('428c')
    expect(detail.textContent).toContain('257c')
  })

  it('dims but never blanks while a refresh is in flight', async () => {
    let release: (() => void) | undefined
    const gate = new Promise<void>((resolve) => (release = resolve))
    let first = true
    await show(async () => {
      if (first) {
        first = false
        return BAG
      }
      await gate
      return BAG
    })
    await userEvent.click(screen.getByText('Refresh'))
    const grid = screen.getByRole('grid', { name: 'bag layout, by verdict' })
    expect(grid.getAttribute('aria-busy')).toBe('true')
    expect(within(grid).getByLabelText(/Divine Orb/)).toBeInTheDocument()
    release!()
  })
})

describe('sync states, on the screen', () => {
  it('says how long ago when fresh', async () => {
    await show()
    expect(screen.getByText(/synced .* ago/)).toBeInTheDocument()
  })

  it('says "no change since HH:MM" rather than claiming a refresh', async () => {
    await show()
    await userEvent.click(screen.getByText('Refresh'))
    await waitFor(() => expect(screen.getByText(/no change since/)).toBeInTheDocument())
    expect(screen.queryByText(/refreshed/i)).toBeNull()
  })

  it('says the fetch did not happen when the answer was cache', async () => {
    await show(async () => ({ ...BAG, stale: true }))
    expect(screen.getByText(/cached — nothing was fetched/)).toBeInTheDocument()
    // ...and still shows the bag.
    expect(screen.getByText('Divine Orb')).toBeInTheDocument()
  })

  it('reports a failure with its reason, and offers a retry', async () => {
    installClient(
      harness(async () => {
        throw new TransportError('no league on the character', { kind: 'LeagueUnknownError' })
      }).client,
    )
    render(<BagScreen />)
    await waitFor(() => expect(screen.getByText(/could not read the bag/)).toBeInTheDocument())
    // Twice: the banner states it and the error block repeats it beside the retry.
    expect(screen.getAllByText(/no league on the character/).length).toBeGreaterThan(0)
    expect(screen.getByText('Try again')).toBeInTheDocument()
  })

  it('counts the limiter down and refuses the press, rather than swallowing it', async () => {
    const attempts = { count: 0 }
    installClient(
      harness(async () => {
        attempts.count += 1
        throw new TransportError('rate limited: retry in 47s', {
          kind: 'RateLimited',
          retryAfter: 47,
        })
      }).client,
    )
    render(<BagScreen />)
    await waitFor(() =>
      expect(screen.getByText(/the rate limiter refused this request/)).toBeInTheDocument(),
    )
    expect(screen.getByText(/rate limited — retry in 47s/)).toBeInTheDocument()

    await userEvent.click(screen.getByText('Try again'))
    // Still one attempt: the control is disabled while the countdown runs, so the
    // press is refused visibly instead of disappearing.
    expect(attempts.count).toBe(1)
  })

  it('re-appraises when the backend says the bag may have changed', async () => {
    let calls = 0
    const built = harness(async () => {
      calls += 1
      return BAG
    })
    installClient(built.client)
    render(<BagScreen />)
    await waitFor(() => expect(calls).toBe(1))
    built.fire('sync_complete')
    await waitFor(() => expect(calls).toBe(2))
  })
})

describe('trash', () => {
  it('is collapsed to a few rows and says how many it hid', async () => {
    await show()
    await reveal('trash')
    expect(within(section('trash')).getByText(/show \d+ more items?/)).toBeInTheDocument()
  })

  it('expands on request', async () => {
    await show()
    await reveal('trash')
    await userEvent.click(within(section('trash')).getByText(/show \d+ more items?/))
    await waitFor(() => expect(within(section('trash')).queryByText(/more items/)).toBeNull())
  })
})

describe('an empty bag', () => {
  it('says so rather than showing a blank page', async () => {
    await show(async () => ({
      ...BAG,
      items: [],
      counts: { keep: 0, check: 0, trash: 0, unpriceable: 0, not_loot: 0 },
      total_chaos: 0,
      total_divine: 0,
      unpriceable_count: 0,
      unpriceable_stack: 0,
      pricing_count: 0,
      no_listings_count: 0,
      total_is_floor: false,
    }))
    expect(screen.getByText('nothing in the backpack')).toBeInTheDocument()
    expect(screen.getByText('the bag is empty')).toBeInTheDocument()
  })
})

// -- the module's own mapping ---------------------------------------------------

describe('model', () => {
  it('splits check on whether a number exists, not on the gate alone', () => {
    const rows = BAG.items.filter((item) => item.verdict === 'check')
    for (const item of rows) {
      expect(checkLane(item)).toBe(
        item.pricing || item.valuation.unpriceable ? 'unknown' : 'priced',
      )
    }
  })

  it('subtotals a block over its priced rows only', () => {
    const unpriceable = blocksOf(BAG).find((block) => block.verdict === 'unpriceable')!
    expect(unpriceable.subtotal).toBe(0)
    expect(unpriceable.units).toBe(BAG.unpriceable_stack)
  })

  it('builds a glyph from initials, so every scarab is not "Sc"', () => {
    expect(glyphFor('Divine Orb')).toBe('DO')
    expect(glyphFor('Scarab of Monstrous Lineage')).toBe('SM')
    expect(glyphFor("Merrick's Ducat")).toBe('MD')
  })

  it('shows a stack-aware price, not a unit price', () => {
    const divine = BAG.items.find((item) => item.name === 'Divine Orb')!
    expect(toRow(divine, BAG.divine_rate).price?.chaos).toBe(divine.total_chaos)
    expect(divine.total_chaos).toBeGreaterThan(214)
  })
})

// -- the first live appraisal's bugs, in the surface that has to show them ---------

describe('bug 2: a tier-3 answer of "nothing" is terminal, not pending', () => {
  it('draws a finished empty search differently from an outstanding one', async () => {
    await show()
    const block = section('check · no price yet')
    const settled = rowFor('Dire Grasp', block)
    const outstanding = rowFor('Rift Shroud', block)

    // The one that finished: no ellipsis, no promise, and never a zero.
    expect(settled.textContent).toContain('∅')
    expect(settled.textContent).not.toContain('⋯')
    expect(settled.textContent).not.toContain('pricing…')
    expect(settled.textContent).not.toContain('0c')

    // The one that has not: unchanged, because the fix must not delete the true case.
    expect(outstanding.textContent).toContain('⋯')
    expect(outstanding.textContent).toContain('pricing…')
  })

  it('marks the finished row so the player knows we looked', async () => {
    await show()
    const settled = rowFor('Dire Grasp', section('check · no price yet'))
    expect(settled.textContent).toContain('no listings')
  })

  it('says in the detail pane that the search finished, and what it asked', async () => {
    await show()
    const detail = await inspect('Dire Grasp')
    expect(detail.textContent).toContain('no matching listings')
    expect(detail.textContent).not.toContain('still outstanding')
    // The query is carried through, so a surprising answer is traceable.
    expect(detail.textContent).toContain('max life')
  })

  it('counts finished-and-empty rows separately from still-pricing ones', () => {
    const note = floorNote(BAG)!
    expect(note).toMatch(/still pricing/)
    expect(note).toMatch(/no matching listings/)
    // Two clauses, two counts — not one number describing both.
    expect(note).toMatch(new RegExp(`${BAG.pricing_count} items? still pricing`))
    expect(note).toMatch(new RegExp(`${BAG.no_listings_count} items? searched`))
  })

  it('drops the still-pricing clause when nothing is outstanding', () => {
    const settled = { ...BAG, pricing_count: 0 }
    const note = floorNote(settled)!
    expect(note).not.toMatch(/still pricing/)
    expect(note).toMatch(/no matching listings/)
  })
})

describe('bug 3: a quest item is not a loot decision', () => {
  it('never appears under an instruction to sell or destroy it', async () => {
    await show()
    await reveal('trash')
    expect(within(section('trash')).queryByText('The Mortinomicon Exitio Immortalis')).toBeNull()
    expect(
      within(section('unpriceable')).queryByText('The Mortinomicon Exitio Immortalis'),
    ).toBeNull()

    const block = section('not loot')
    expect(within(block).getByText('The Mortinomicon Exitio Immortalis')).toBeInTheDocument()
    // ...and the block it *is* in is not one of the four that ask for an action.
    // The headline itself is asserted below, at the model level: only `full`
    // renders section descriptions, so the DOM is the wrong place to look for it.
    expect(within(block).queryByText(VERDICT_HEADLINE.trash)).toBeNull()
  })

  it('gives the block a headline that instructs nothing', () => {
    const block = blocksOf(BAG).find((entry) => entry.verdict === 'not_loot')!
    // The copy, at the model level, because only `full` renders descriptions.
    expect(copyFor(block).headline).toBe('not loot — nothing to sell, nothing to vendor')
  })

  it('shows no money for it, not even a zero, and says why at both densities', async () => {
    await show()
    const row = rowFor('The Mortinomicon Exitio Immortalis', section('not loot'))
    expect(row.textContent).not.toContain('0c')
    // `compact` has no reason column, so the fact travels as a mark — otherwise the
    // 300 px row is a name, a category and a bare dash.
    expect(row.textContent).toContain('not loot')
  })

  it('carries the reason wherever there is room for a sentence', async () => {
    await show()
    const detail = await inspect('The Mortinomicon')
    expect(detail.textContent).toContain('cannot be traded or vendored')
  })

  it('keeps it in the grid, because the grid is a map of the bag', async () => {
    await show()
    const grid = screen.getByRole('grid', { name: 'bag layout, by verdict' })
    expect(within(grid).getByLabelText(/The Mortinomicon/)).toBeInTheDocument()
  })

  it('gives it a tally slot, so the state is visible even at zero', () => {
    const entry = tallyOf(BAG).find((row) => row.id === 'not_loot')
    expect(entry).toBeDefined()
    expect(entry!.count).toBe(BAG.counts.not_loot)
    expect(tallyOf({ ...BAG, counts: { ...BAG.counts, not_loot: 0 } }).map((r) => r.id)).toContain(
      'not_loot',
    )
  })
})
